# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentimage',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/home/'),
        ),
    ]
